# Generated by Django 4.0.3 on 2022-06-12 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('msg', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='')),
                ('solo', models.ImageField(upload_to='')),
            ],
        ),
    ]
