# Generated by Django 4.0.3 on 2022-06-12 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='solo',
        ),
    ]
